package br.com.ucsal.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseUtil {

	
    private static final String URL = "jdbc:hsqldb:mem:lojadb";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    // Inicializa o banco de dados e cria a tabela produtos
    public static void iniciarBanco() {
    	// Carrega o driver do HSQLDB
        try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

        // Criação da tabela e inserção de dados iniciais
        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            stmt.executeUpdate("CREATE TABLE produtos (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "nome VARCHAR(50), " +
                    "preco DOUBLE" +
                    ")");


            stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Notebook', 3500.00);");
            stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Smartphone', 1500.00);");

            System.out.println("Banco de dados inicializado com sucesso!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Retorna uma conexão ativa com o banco de dados
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    
    
    
}

